{% set name = "django-stubs-ext" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/django-stubs-ext-{{ version }}.tar.gz
  sha256: 9bd7418376ab00b7f88d6d56be9fece85bfa0c7c348ac621155fa4d7a91146f2

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - django
    - python >=3.6
    - typing-extensions

test:
  imports:
    - django_stubs_ext
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/typeddjango/django-stubs
  summary: Monkey-patching and extensions for django-stubs
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
